default: &default
  pool: 5
  timeout: 10000
  adapter: mysql2
  encoding: utf8
  host: localhost
  username: root
  password:

development:
  <<: *default
  database: Blog_development

test:
  <<: *default
  database: Blog_test

production:
  <<: *default
  database: <%= ENV['BLOG_DB_NAME'] %>
  username: <%= ENV['BLOG_DB_USERNAME'] %>
  password: <%= ENV['BLOG_DB_PASSWORD'] %>